development:
  facebook:
    app_id: "548927411872156"
    app_secret: "0ec2a1378c630d0e62574f7321aa914b"
  google:
    app_id: "721520450986.apps.googleusercontent.com"
    app_secret: "9b8fVLbNGMDS3IVgxLyNKqGg"
  twitter:
    app_id: "oXw5sbzFyvG56T8mNA4bw"
    app_secret: "iD2cOWcvC2lQaNWsszjMr6mIoM4iOF5luTPmEg8m0c"
test:
  facebook:
    app_id: "429968693767890"
    app_secret: "2179362080d6081a086e1e62d1c6d0ab"
  google:
    app_id: "920097647662.apps.googleusercontent.com"
    app_secret: "A_6A7lujArGVGhYn2HR7ci7R"

# TODO: change this when the app go live.
production:
  facebook:
    app_id: "x"
    app_secret: "y"
  google:
    app_id: "z"
    app_secret: "t"
