#development: &sandbox
#  login: htluan2605_api1.gmail.com
#  password: 1382519777
#  signature: An5ns1Kso7MWUdW4ErQKJJJ4qi4-AlFw0KidIM2sitAJn0cpxJ8hjGJK
#  sandbox: true

development: &default
  mode: sandbox
  # Credentials for Classic APIs
  app_id: 'APP-80W284485P519543T'
  username: 'thanhquang1988-facilitator_api1.gmail.com'
  password: '1382528021'
  signature: 'An5ns1Kso7MWUdW4ErQKJJJ4qi4-Ad7m2ySnOE2SGXa-JSfN63QqCaXX'
  sandbox_email_address: 'thanhquang1988@gmail.com'
test:
  <<: *default

production:
  <<: *default
  mode: sandbox